image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: DOSlU041NY0WKjv9njrNqj14CLEzrF4ogZsbvqIXnNLd492oNlQf4dD5yr7TSK/S
  SignClientSecret:
    secure: FHkjtWF9Y3ZjXI9muiLfpnpUZPNz2NWGWJlLRRaMs5E=
  SignClientUser:
    secure: 8dxp/8LR7WGOUvOz7gdmd3PlqRM4yH4Tmq52eNTuqMn1UfX9v2LbQDmk7VG/mTUX

init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true

only_commits:
  files:
    - Rx.NET/**/*
    - '*'

skip_tags: true

skip_commits:
  files:
    - '**/*.md'

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\Rx.NET\Source\build-new.ps1

test: off
artifacts:
- path: .\artifacts\*.nupkg
  
deploy:
- provider: NuGet
  server: https://dotnet.myget.org/F/rx/api/v2/package
  on:
    branch: master  
  api_key:
    secure: 5qZfZf9XVtN+h/UHwocrEBZjaZCajJg9fZbLDPigoew1NG7PzWQxMv1kLQJW6eWE
  symbol_server: https://dotnet.myget.org/F/rx/symbols/api/v2/package
  
- provider: NuGet
  server: https://dotnet.myget.org/F/rx/api/v2/package
  on:
    branch: develop  
  api_key:
    secure: 5qZfZf9XVtN+h/UHwocrEBZjaZCajJg9fZbLDPigoew1NG7PzWQxMv1kLQJW6eWE
  symbol_server: https://dotnet.myget.org/F/rx/symbols/api/v2/package  