image: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: DOSlU041NY0WKjv9njrNqj14CLEzrF4ogZsbvqIXnNLd492oNlQf4dD5yr7TSK/S
  SignClientSecret:
    secure: oR9TMOkkvP/prmXyMT+p6mQhjyw3JDLbuywezBABvXzkvNsdNZgi2yPaHhgaofrb

skip_branch_with_pr: true

skip_commits:
  files:
    - '**/*.md'
    
skip_non_tags: true

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1

test: off
artifacts:
- path: .\artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server: https://dotnet.myget.org/F/rx/api/v2/package
  on:
    appveyor_repo_tag: true
  api_key:
    secure: 5qZfZf9XVtN+h/UHwocrEBZjaZCajJg9fZbLDPigoew1NG7PzWQxMv1kLQJW6eWE
  symbol_server: https://dotnet.myget.org/F/rx/symbols/api/v2/package